TODO

1. EN EL FRONT REVISAR LOS CONSOLE LOG EN ONROUTE
2. EVITAR LA DUPLICACION DE CIDIGO QUE SE PUEDE HACER CON UNA FUNCION QUE RENDERICE ALGO SI EL ROUTE ES REGISTER OR SIGNIN.
COMO EN LA LOGICA DE LO QUE APP RENCEDIZA SEGUN EL ROUTE.
EN EL REGISTRO Y LOGIN AGREGAR TOUPPERCASE O SU CONTRARIO PARA QUE TRANSFORME SI INGRESO PALABRAS CON MAYUSCULAS A MINUSCULAS